### ISSUE TITLE
conflicting ID-types for attribute "id" of f:* elements

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-schema#2]
In Oxygen using the default validation settings, our schema fails with the message _conflicting ID-types for attribute "id"_ for one of the elements from the Faust namespace. This is https://github.com/relaxng/jing-trang/issues/211.

As a workaround, go to Options → Preferences in Oxygen, and on the XML / XML Parser / RELAX NG page, uncheck _Check ID/IDREF_. 

The root of the trouble is this excerpt in the generated Relax NG:

```xml
   <define name="anyElement-xenoData">
      <element>
         <anyName>
            <except>
               <nsName ns="http://www.tei-c.org/ns/1.0"/>
               <name ns="http://www.tei-c.org/ns/Examples">egXML</name>
            </except>
         </anyName>
         <zeroOrMore>
            <attribute>
               <anyName/>
            </attribute>
         </zeroOrMore>
         <zeroOrMore>
            <choice>
               <text/>
               <ref name="anyElement-xenoData"/>
            </choice>
         </zeroOrMore>
      </element>
   </define>
```
This allows our f:*-Elements, but it allows for them to have any attribute of any type which effectively allows `xml:id` to be anything, not only `xs:ID`. Since we need the `f:` elements there for the testimony data, I currently don’t see a solution.

**Comment by thvitt** [comment]
also cf. https://github.com/TEIC/TEI/issues/1399

**Comment by gerritbruening** [comment]
This seems to prevent me from validating a file after making a change to adjust it to schema, right?

**Comment by thvitt** [comment]
> As a workaround, go to Options → Preferences in Oxygen, and on the XML / XML Parser / RELAX NG page, uncheck Check ID/IDREF.

**Comment by gerritbruening** [comment]
Thanks, done!

**Comment by thvitt** [comment]
As outlined [in this e-mail thread](https://lists.oasis-open.org/archives/office/200808/msg00024.html), the obvious solution – explicitely defining the datatype of xml:ID for the _any_ elements also isn’t compatible with the DTD compatibility layer.

So effectively, this issue could only be fixed by explicitly forbidding the faust namespace in the xenoData element, which would require modifications in testimony processing, which I won’t implement for 1.0rc.
